"""Next.js helper macros for Bazel targets."""

load("@aspect_rules_js//js:defs.bzl", "js_run_binary", "js_run_devserver")

def next_app(
        name,
        srcs,
        data,
        next_js_binary,
        next_bin,
        next_build_out = ".next",
        next_export_out = "out",
        **kwargs):
    """Creates Bazel targets that wrap the Next.js CLI.

    Args:
        name: Base name for the generated targets.
        srcs: Source files or groups to expose to the Next CLI.
        data: Runtime files such as configs and npm packages.
        next_js_binary: `js_binary` for `next` (typically generated by rules_js).
        next_bin: Path to the Next CLI relative to the package (used for dev/start servers).
        next_build_out: Output directory created by `next build`.
        next_export_out: Output directory created by `next export`.
        **kwargs: Extra attributes propagated to every generated target.
    """

    tags = kwargs.pop("tags", [])

    js_run_binary(
        name = name,
        tool = next_js_binary,
        args = ["build"],
        srcs = srcs + data,
        out_dirs = [next_build_out],
        chdir = native.package_name(),
        tags = tags,
        **kwargs
    )

    js_run_devserver(
        name = "{}_dev".format(name),
        command = next_bin,
        args = ["dev"],
        data = srcs + data,
        chdir = native.package_name(),
        tags = tags,
        **kwargs
    )

    js_run_devserver(
        name = "{}_start".format(name),
        command = next_bin,
        args = ["start"],
        data = data + [name],
        chdir = native.package_name(),
        tags = tags,
        **kwargs
    )

    js_run_binary(
        name = "{}_export".format(name),
        tool = next_js_binary,
        args = ["export"],
        srcs = data + [name],
        out_dirs = [next_export_out],
        chdir = native.package_name(),
        tags = tags + ["manual"],
        **kwargs
    )
