version: '3'

# If the task file is run via the root task file, the dir attribute is required to prevent the task file being run from the root.
# It is not required when running the task file directly as opposed as from root.

vars:
  FRONTEND_DIR: ./apps/web

tasks:
  install:
    desc: "Installs the packages and dependencies for the next.js frontend"
    run: when_changed
    cmds:
      - pnpm install
    sources:
      - package.json
      - pnpm-lock.yaml
    generates:
      - node_modules

  build:
    desc: "Builds the next.js frontend"
    deps: [install]
    cmds:
      - pnpm exec nx build web

  test:
    desc: "Runs the tests for the frontend"
    deps: [install]
    cmds:
      - pnpm exec nx test web

  lint:
    desc: "Runs the linter for the frontend"
    deps: [install]
    cmds:
      - pnpm exec nx lint web

  deploy:
    dir: "{{.FRONTEND_DIR}}"
    desc: "Deploys the frontend application to Vercel (runs lint, test, and build first)"
    deps: [lint, test, build]
    cmds:
      - npx vercel deploy --prod --yes
