version: '3'

vars:
  FRONTEND_DIR: ./apps/web
  BACKEND_DIR: ./apps/api
  LAMBDA_DIR: ./apps/api/internal/lambda
  GIT_SHA:
    sh: git rev-parse --short HEAD
  DOCKER_TAG: "{{.GIT_SHA}}"

  AWS_ACCOUNT_ID: "750969166615"
  AWS_REGION: eu-north-1

  ECR_REPOSITORY: build-tool-test
  ECR_REGISTRY: "{{.AWS_ACCOUNT_ID}}.dkr.ecr.{{.AWS_REGION}}.amazonaws.com"
  DOCKER_IMAGE: "{{.ECR_REGISTRY}}/{{.ECR_REPOSITORY}}"

  ECS_SERVICE: build-tool-test-service-excyce51
  ECS_CLUSTER: build-tool-test


includes:
  frontend: ./apps/web/Taskfile.yml
  backend: ./apps/api/Taskfile.yml
  lambda: ./apps/api/internal/lambda/Taskfile.yml

tasks:
  default:
    cmds:
      - task: help

  help:
    desc: List common tasks
    cmds:
      - |
          echo "Frontend: task build | test | lint | dev | deploy"
          echo "Backend:  task build  | test | lint | docker | deploy"
          echo "Lambda:   task build   | test | deploy"
          echo "Pipelines: task ci | task deploy"
    silent: true

  ci:
    desc: Runs the full test and linting suite for all services.
    deps:
      - frontend:test
      - frontend:lint
      - backend:test
      - backend:lint

  deploy:
    desc: Deploy frontend to Vercel, backend to ECS, and Lambda (CI only)
    deps:
      - ci
    preconditions:
      - sh: '[ "${CI:-}" = "true" ]'
        msg: "Deploy can only be run in CI (CI env var must be set)."
    cmds:
      - task frontend:deploy
      - task backend:deploy

