version: '3'

vars:
  BACKEND_DIR: ./apps/api
  AWS_REGION: eu-north-1

includes:
  frontend: ./apps/web/Taskfile.yml
  backend: ./apps/api/Taskfile.yml
  lambda: ./apps/api/internal/lambda/Taskfile.yml

tasks:
  default:
    cmds:
      - task: help

  help:
    desc: List common tasks
    cmds:
      - |
          echo "Frontend: task build | test | lint | dev | deploy"
          echo "Backend:  task build  | test | lint | docker | deploy"
          echo "Lambda:   task build   | test | deploy"
          echo "Pipelines: task ci | task deploy"
    silent: true

  ci:
    desc: Runs the full test and linting suite for all services.
    deps:
      - frontend:test
      - frontend:lint
      - backend:test
      - backend:lint
      - lambda:test
      - lambda:lint

  deploy:
    desc: Deploy frontend to Vercel, backend to ECS, and Lambda (CI only)
    deps:
      - ci
    cmds:
      - task frontend:deploy
      - task backend:deploy
      - task lambda:deploy

