version: "3"

includes:
  web: ./apps/web/Taskfile.yml
  api: ./apps/api/Taskfile.yml
  lambda: ./apps/api/internal/lambda/Taskfile.yml

tasks:
  default:
    cmds: [task -l]
    silent: true

  ci:
    desc: Run tests + lint for all services
    cmds:
      - task web:ci
      - task api:ci
      - task lambda:ci

  deploy:
    desc: Deploy web + api + lambda
    cmds:
      - task ci
      - task web:deploy
      - task api:deploy
      - task lambda:deploy
