// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Book defines model for Book.
type Book struct {
	Author    string             `json:"author"`
	CreatedAt time.Time          `json:"createdAt"`
	Currency  string             `json:"currency"`
	Id        openapi_types.UUID `json:"id"`
	Price     float32            `json:"price"`
	Stock     int                `json:"stock"`
	Title     string             `json:"title"`
	UpdatedAt time.Time          `json:"updatedAt"`
}

// BookCreate defines model for BookCreate.
type BookCreate struct {
	Author   string  `json:"author"`
	Currency string  `json:"currency"`
	Price    float32 `json:"price"`
	Stock    int     `json:"stock"`
	Title    string  `json:"title"`
}

// BookUpdate defines model for BookUpdate.
type BookUpdate struct {
	Author   *string  `json:"author,omitempty"`
	Currency *string  `json:"currency,omitempty"`
	Price    *float32 `json:"price,omitempty"`
	Stock    *int     `json:"stock,omitempty"`
	Title    *string  `json:"title,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// CreateBookJSONRequestBody defines body for CreateBook for application/json ContentType.
type CreateBookJSONRequestBody = BookCreate

// UpdateBookJSONRequestBody defines body for UpdateBook for application/json ContentType.
type UpdateBookJSONRequestBody = BookUpdate
