version: '3'

# If the task file is run via the root task file, the dir attribute is required to prevent the task file being run from the root.
# It is not required when running the task file directly as opposed as from root.

vars:
  LAMBDA_DIR: ./internal/lambda/bookemailer
  LAMBDA_FUNCTION: built-tool-test-email

tasks:
  lint:
    desc: Lint Lambda code
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - golangci-lint run ./{{.LAMBDA_DIR}}/...

  test:
    desc: Test Lambda code
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go test ./{{.LAMBDA_DIR}}/...

  build:
    desc: Build Lambda binary
    dir: "{{.BACKEND_DIR}}/{{.LAMBDA_DIR}}"
    deps: [lint, test]
    cmds:
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bootstrap .

  zip:
    desc: Zip Lambda binary
    dir: "{{.BACKEND_DIR}}/{{.LAMBDA_DIR}}"
    deps: [build]
    cmds:
      - zip deployment.zip bootstrap

  deploy:
    desc: Deploy Lambda
    dir: "{{.BACKEND_DIR}}/{{.LAMBDA_DIR}}"
    deps: [zip]
    cmds:
      - |
          aws lambda update-function-code \
            --function-name {{.LAMBDA_FUNCTION}} \
            --zip-file fileb://deployment.zip \
            --region {{.AWS_REGION}} \
            --no-cli-pager
