/* eslint-disable */
// Code generated by packages/contracts/codegen.ts; DO NOT EDIT.
export interface components {
  schemas: {
    Book: {
      id: string;
      title: string;
      author: string;
      price: number;
      currency: string;
      stock: number;
      created_at: string;
      updated_at: string;
    };
    BookResponse: {
      data: components["schemas"]["Book"];
    };
    BookListResponse: {
      data: components["schemas"]["Book"][];
      next_cursor?: string | null;
    };
    BookCreateRequest: {
      title: string;
      author: string;
      price: number;
      currency: string;
      stock: number;
    };
    BookUpdateRequest: components["schemas"]["BookCreateRequest"];
    PurchaseRequest: {
      quantity: number;
      customer_id?: string;
    };
    PurchaseAcceptedResponse: {
      message_id: string;
      status: "accepted";
    };
    ErrorResponse: {
      error: string;
      code: string;
      details?: Record<string, unknown>;
    };
    HealthResponse: {
      status: string;
    };
  };
}

export interface paths {
  "/healthz": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["HealthResponse"];
          };
        };
      };
    };
  };
  "/books": {
    get: {
      parameters: {
        query: {
          limit?: number;
          cursor?: string;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["BookListResponse"];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["BookCreateRequest"];
        };
      };
      responses: {
        201: {
          content: {
            "application/json": components["schemas"]["BookResponse"];
          };
        };
      };
    };
  };
  "/books/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["BookResponse"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["BookUpdateRequest"];
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["BookResponse"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        204: Record<string, never>;
      };
    };
  };
  "/books/{id}/purchase": {
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["PurchaseRequest"];
        };
      };
      responses: {
        202: {
          content: {
            "application/json": components["schemas"]["PurchaseAcceptedResponse"];
          };
        };
      };
    };
  };
}

export type operations = never;
