/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/books": {
    /** List books */
    get: operations["listBooks"];
    /** Create a book */
    post: operations["createBook"];
  };
  "/books/{id}": {
    /** Get a book */
    get: operations["getBook"];
    /** Update a book */
    put: operations["updateBook"];
    /** Delete a book */
    delete: operations["deleteBook"];
    parameters: {
      path: {
        id: string;
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Book: {
      /** Format: uuid */
      id: string;
      title: string;
      author: string;
      price: number;
      /** @default USD */
      currency: string;
      stock: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    BookCreate: {
      title: string;
      author: string;
      price: number;
      /** @default USD */
      currency: string;
      stock: number;
    };
    BookUpdate: {
      title?: string;
      author?: string;
      price?: number;
      currency?: string;
      stock?: number;
    };
    Error: {
      message: string;
    };
  };
  responses: {
    /** @description Bad request */
    BadRequest: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Resource not found */
    NotFound: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** List books */
  listBooks: {
    responses: {
      /** @description A list of books */
      200: {
        content: {
          "application/json": {
            books: components["schemas"]["Book"][];
          };
        };
      };
      400: components["responses"]["BadRequest"];
    };
  };
  /** Create a book */
  createBook: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["BookCreate"];
      };
    };
    responses: {
      /** @description Book created */
      201: {
        content: {
          "application/json": components["schemas"]["Book"];
        };
      };
      400: components["responses"]["BadRequest"];
    };
  };
  /** Get a book */
  getBook: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Book details */
      200: {
        content: {
          "application/json": components["schemas"]["Book"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  /** Update a book */
  updateBook: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BookUpdate"];
      };
    };
    responses: {
      /** @description Updated book */
      200: {
        content: {
          "application/json": components["schemas"]["Book"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
    };
  };
  /** Delete a book */
  deleteBook: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Book deleted */
      204: {
        content: never;
      };
      404: components["responses"]["NotFound"];
    };
  };
}
